service: MercuryParserAPI-node12

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  profile: default
  stage: prod # default deployment environment
  vpc:
    securityGroupIds:
      - ${self:custom.Global.mySecurityGroupIds.${self:custom.Global.myStage}}
    subnetIds:
      - ${self:custom.Global.mySubnetIds.${self:custom.Global.myStage}.1a}
      - ${self:custom.Global.mySubnetIds.${self:custom.Global.myStage}.1b}
      - ${self:custom.Global.mySubnetIds.${self:custom.Global.myStage}.1c}

plugins:
  - serverless-webpack
  - serverless-offline

functions: ${file(serverless_functions.yml)}

custom: ${file(serverless_variables.yml)}